### ISSUE TITLE
Set Chrome App as Kiosk App

### ISSUE THREAD

**Issue by beaufortfrancois** [g-ortuno/eddystone-chrome-apps-demo#1]
According to https://developer.chrome.com/apps/manifest/kiosk_enabled#Develop, you may want to set `kiosk_enabled` and `kiosk_only` in your manifest.

**Comment by g-ortuno** [comment]
Added a note to the README. You can't launch an app in Kiosk Mode if it's not on the Web Store. [#72727a4](https://github.com/g-ortuno/eddystone-chrome-apps-demo/commit/72727a44a92eacf565ca363f4b1011f8c03278b5)

**Comment by bj32161** [comment]
Hi,
To run manual, I can do from terminal by press CTL-ATL-F2
sudo hciconfig hci0 up
sudo hciconfig hci0 leadv 3
sudo hcitool -i hci0 cmd 0x08 0x0008 1b 02 01 06 03 03 aa fe 13 16 aa fe 10 00 03 67 6f 6f 2e 67 6c 2f 34 51 67 5a 6a 64 00 00 00 00
but the configuration will gone when I reboot my Chrome-box
I tried to find how to permanent setup easy way but no luck. there is only your App-demo and setting Eddystone URL on chrome device. 
Anyway, This is my questions. 
1. How can I compile and run this demo app on my Chrome-box? (sorry I'm new with git and coding)
2. If I already have Kiosk App (Signage) run as Kiosk mode and auto-launch when startup. Can I set this app as 2nd App to run with? (Signage+Physical Web)

Thank you
Panya

**Comment by beaufortfrancois** [comment]
1. You may want to have a look at https://developer.chrome.com/apps/manifest/kiosk_enabled
2. Nope ;(

**Comment by g-ortuno** [comment]
As Francois mentioned you can't run two apps in Kiosk mode at the same time but if you own the code for the Signage app you can incorporate the code from this repo into the Signage App.

**Comment by bj32161** [comment]
Than you. :)
